

GET http://localhost:8094/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZjJkMzEyOWU0MDI1NDBiMGUxM2IzZDAiLCJpYXQiOjE1OTY5OTQ0Nzh9.KsEPhR79blmvL6OcAZJytIWFmXGTzJS8ydk2B-aIqvY

###

POST http://localhost:8094/post  HTTP/1.1
content-type: application/json

{
	"title": "Buzzo Cururu",
	"body": "Buzzo is a zoado but he is very funny"
}

###

POST http://localhost:8094/signup  HTTP/1.1
content-type: application/json

{
	"name": "Buzzo2",
	"email": "buzzo2.cururu@gmail.com",
	"password": "cururu2"
}

###

POST http://localhost:8094/signin  HTTP/1.1
content-type: application/json

{
	"email": "buzzo2.cururu@gmail.com",
	"password": "cururu2"
}
