

GET http://localhost:8094/

###

GET http://localhost:8094/posts/by/5f304f5401bde91cb96b19cb
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZjMwNGY1NDAxYmRlOTFjYjk2YjE5Y2IiLCJpYXQiOjE1OTcyMjc5ODF9.BOINDPULw619FKC0jwz3Cqz-IJLmvlxnOlFrfJPXWUo


###

POST http://localhost:8094/post/new/5f304f5401bde91cb96b19cb  HTTP/1.1
Content-Type: application/x-www-form-urlencoded
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZjMwNGY1NDAxYmRlOTFjYjk2YjE5Y2IiLCJpYXQiOjE1OTcxNDE0MTN9.YaVAU22AKqnig2CIhb5ciAH_oB2GsgHW6riQaA173QM

title="Eu zoei o Buzzo"&body="Porque o Buzzo é forever zoado ahahehaeh, então zoeira never ends"


###

POST http://localhost:8094/signup  HTTP/1.1
content-type: application/json

{
	"name": "gordochuna",
	"email": "gordochuna1.cururu@gmail.com",
	"password": "cururu1"
}

###

POST http://localhost:8094/signin  HTTP/1.1
content-type: application/json

{
	"email": "gordochuna1.cururu@gmail.com",
	"password": "cururu1"
}

###

GET http://localhost:8094/users  HTTP/1.1
content-type: application/json

###

GET http://localhost:8094/user/5f304f5401bde91cb96b19cb  HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZjJkMzEyOWU0MDI1NDBiMGUxM2IzZDAiLCJpYXQiOjE1OTcwMDAwOTh9.hOvJjNZCtKX7kX7tVRtEpZ3pOQRgaKIqfIhGrRZqZ9M

###

PUT http://localhost:8094/user/5f2d3129e402540b0e13b3d0  HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZjJkMzEyOWU0MDI1NDBiMGUxM2IzZDAiLCJpYXQiOjE1OTcwMDAwOTh9.hOvJjNZCtKX7kX7tVRtEpZ3pOQRgaKIqfIhGrRZqZ9M

{
      "name": "mario",
      "email": "mario.cururu1@gmail.com"
      
    }

###

DELETE http://localhost:8094/user/5f304f5401bde91cb96b19cb  HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZjJkMzEyOWU0MDI1NDBiMGUxM2IzZDAiLCJpYXQiOjE1OTcwMDAwOTh9.hOvJjNZCtKX7kX7tVRtEpZ3pOQRgaKIqfIhGrRZqZ9M


